server:
  http_port: 8080
  grpc_port: 8181
  max_send_message_length: 2147483647
  max_receive_message_length: 63554432

enforcer:
  model_file: ${PROJECT_DIR}/configs/enforcer/model.conf
  policy_file: ${PROJECT_DIR}/configs/enforcer/policy.csv

ssl:
  cert_file: ${PROJECT_DIR}/configs/ssl/crt.pem
  private_key_file: ${PROJECT_DIR}/configs/ssl/private.key.pem
  public_key_file: ${PROJECT_DIR}/configs/ssl/public.key.pem

session:
  audience: Enterprise Application
  issuer: Solomonov
  duration: 168h